openworld-community/ows-events

backend/src/controllers/events-state-controller.ts, common/types/event.ts, frontend/src/views/HomeView.vue
Change location type from string to object with string-typed fields city and country;
=> 11: Change location type

backend/server.ts, backend/src/controllers/events-state-controller.ts
Add simple search and endpoint for it;
=> Simple search

backend/server.ts, frontend/src/router/index.ts, frontend/src/services/events.services.ts, frontend/src/views/EventView.vue, frontend/src/views/HomeView.vue
https://github.com/openworld-community/ows-events/issues/37
=> st_37: add empty event template

backend/package-lock.json, backend/package.json, backend/server.ts, backend/src/controllers/image-controller.ts
Add delete image endpoint;
Refactor add image endpoint to multipart/form-data;
=> Change api;

frontend/src/assets/main.css, frontend/src/views/EventView.vue
Make layout for event on its page;
=> Event layout;

frontend/src/views/HomeView.vue
Make layout for card preview on homepage;
=> Card preview;

frontend/src/components/common/button/ImageLoader.vue, frontend/src/components/common/input/CustomInput.vue, frontend/src/components/common/input/DatalistInput.vue, frontend/src/components/modal/NewEventModal.vue, frontend/src/helpers/dates.ts, frontend/src/services/events.services.ts, frontend/src/views/EventView.vue
=> st 5: add event changing

Dockerfile, deploy.sh, docker-compose.prod.yml
=> Add docker and deploy script;

.gitignore, docker-compose.prod.yml
Add persistent data storage for prod;
=> Add persistent data storage for prod;

package-lock.json, package.json
Добавил либу concurrently чтобы запускать бэк и фронт одной командой dev
=> Concurrently 

frontend/src/components/common/button/ImageLoader.vue, frontend/src/components/header/languageSelector.vue, frontend/src/components/home/AdCard.vue, frontend/src/components/home/EventPreviewCard.vue, frontend/src/components/modal/NewEventModal.vue, frontend/src/i18n/locales/ru/index.ts, frontend/src/views/HomeView.vue
=> заменил ключи на змейку

frontend/src/assets/less/blocks/input.less, frontend/src/assets/less/global.less, frontend/src/assets/less/variables.less, frontend/src/components/common/button/ImageLoader.vue, frontend/src/components/common/icon/Icon.vue, frontend/src/components/common/input/CustomInput.vue, frontend/src/components/header/CommonHeader.vue, frontend/src/components/header/SubscriptionExpired.vue, frontend/src/components/home/EventPreviewCard.vue, frontend/src/i18n/locales/ru/index.ts, frontend/src/views/AboutView.vue, frontend/src/views/EventView.vue, frontend/src/views/HomeView.vue
Поправила верстку и баги инпутов
=> Hotfix: layout

frontend/src/assets/less/app.less, frontend/src/assets/less/blocks/modal.less, frontend/src/assets/less/variables.less, frontend/src/components/modal/NewEventModal.vue, frontend/src/components/modal/RegistrationModal.vue, frontend/src/i18n/locales/ru/index.ts, frontend/src/router/index.ts, frontend/src/views/EventView.vue
Сделаны стили для маржинов, Стили модалки вынесены в блоки, в идеале сделать кастомный компонент.
=> Убрана страница регистрации, вместо неё модалка

backend/server.ts, backend/src/controllers/file-db-controller.ts
Нужен тест на реальном окружении (демо)
=> add redirect when 404;

frontend/src/App.vue, frontend/src/assets/less/blocks/modal.less, frontend/src/assets/less/global.less, frontend/src/assets/less/variables.less, frontend/src/components/common/button/CustomButton.vue, frontend/src/components/home/EventPreviewCard.vue, frontend/src/views/EventView.vue
=> St 160: add event card layout

.dockerignore, .githooks/README.md, .githooks/pre-commit, .github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/code-review-merge.yml, .github/workflows/code-review-push.yml
Added super-linter for local checking at pre-commit stage and in github actions. 
Also .dockerignore
=> Linters for CodeReview

frontend/components/header/LanguageSelector.vue, frontend/plugins/i18n.ts
Добавил composable в вызов перевода, чтоб триггерить ререндер у Вью
=> дорогая я сломал смену языка пользователя( но починил )

frontend/.env.dev, frontend/package.json, package.json
add possibility to run frontend without docker;
=> hotfix dev;

frontend/components/modal/Event.vue, frontend/components/modal/Registration.vue, frontend/pages/event/[id].vue, frontend/pages/index.vue, frontend/utils/events.ts
Выпилила хранение информации о созданных ивентах в localStorage (теперь права на редактирование и удаление даются при совпадении userId в cookies и ивенте).
Пофиксила баг #224
=> Authorization: last fixes

auth-bot/Dockerfile, bot-status-checker/src/index.ts, docker-compose.prod.yml
Fix eslint in bot-status-checker
=> Add config for prod;

frontend/components/common/ui/BaseInput/BaseInput.vue, frontend/components/common/ui/BaseSelect/BaseSelect.vue, frontend/components/common/ui/Datepicker/Datepicker.vue, frontend/components/common/ui/Datepicker/types/types.ts, frontend/i18n/locales/ru/index.ts, frontend/package-lock.json, frontend/package.json, frontend/utils/dateFormat.ts
Добавила дейтпикер
немного отрефакторила инпут и селектор
=> WIP #213 datepicker

.github/workflows/deploy-demo.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, auth-bot/src/index.ts, backend/.env.dev, docker-compose.demo.yml, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.test.yml
Add .env.dev file for local development without docker;
=> Fix single bot with wrong tokens issue;

frontend/nuxt.config.ts
=> St 317: add metrics

backend/package-lock.json, backend/package.json, backend/src/const/vars.ts
Add dotenv usage for .env.dev file
=> Add dotenv package;

frontend/components/common/Button.vue, frontend/components/modal/Authorisation.vue, frontend/i18n/locales/ru/index.ts
Сделала, потестила, насколько могла. Вроде, всё работает, как надо.
=> St 353 authorisation modal styling

frontend/nuxt.config.ts, frontend/package-lock.json, frontend/package.json, frontend/pages/event/[id].vue
Добавила модуль для интеграции метрик https://github.com/nuxt-modules/plausible, подключила отслеживание кликов по кнопке "связаться"
#334
=> St 334: add redirect metrics

frontend/components/common/ui/TextArea.vue, frontend/components/modal/Event.client.vue, frontend/utils/prices.ts
#377 
Сделала поля "описание" и "цена" обязательными при создании ивента, сделала отображение плашки "цена не указана" возможным только для распаршенных ивентов, когда price не приходит
=> St 377 make fields description and price required

common/types/user.ts, frontend/pages/event/[id].vue
=> St 432 fix peredelanoconf manage actions

frontend/assets/less/global.less, frontend/pages/event/[id].vue
=> St 423: fix event page layout

frontend/components/modal/ui/ModalSection.vue
=> St 430: fix form fields layout for android

backend/src/rest/v1/events/schema.ts, backend/src/server.ts
Fix moderation ui path resolving
=> Fix swagger find event description;

frontend/components/modal/Event.client.vue, frontend/utils/prices.ts
При создании ивента может приходить "0" или цена в формате "10".
С парсинга может приходить "", "0" или цена в форматах "10" или "10 RSD/EUR/€" , либо интервалы цены.
Обработка происходит следующим образом:
"" - "Цена не указана"
"0" - "Бесплатно"
"10" - "10 RSD"
"10 RSD/EUR/€" - "10 RSD/EUR/€"
=> Fix price handler according to parcing data

frontend/components/common/ui/DateTimepicker.vue
=> St 429: close datetimepicker on keydown enter

frontend/components/common/ui/BaseInput.vue, frontend/components/modal/Event.client.vue
fixes #455 
Ограничила длину инпута "стоимость" 10 символами
=> St 455: add max length for price input

frontend/components/common/Button.vue, frontend/components/common/ErrorToast.vue, frontend/components/common/Icon.vue, frontend/components/common/Input.vue, frontend/components/common/ui/BaseInput.vue, frontend/components/common/ui/DateTimepicker.vue, frontend/components/header/Common.vue, frontend/components/header/navigation/NavItem.vue, frontend/components/home/Filter.vue, frontend/components/home/Search.vue, frontend/composables/i18n.ts, frontend/i18n/i18n.d.ts, frontend/i18n/locales/ru/index.ts, frontend/pages/index.vue, frontend/stores/location.store.ts, frontend/utils/index.ts
=> Bug fix bundle 😎

frontend/components/common/ErrorToast.vue, frontend/components/common/ImageLoader.vue, frontend/components/header/Common.vue, frontend/components/home/Filter.vue, frontend/components/modal/Registration.vue, frontend/pages/event/[id].vue
=> St 463 remove gaps in css

frontend/components/common/ui/BaseSelect.vue, frontend/components/home/Filter.vue
=> St 465: add select dropdown position

frontend/utils/dates.ts
* Fix timezones
Co-authored-by: igor.la <igor.la@fora-soft.com>
Co-authored-by: Huge Letters <ckuka71@gmail.com>
=> Fix timezones (#486)

frontend/utils/dates.ts
=> yet another timezone fix

frontend/components/modal/Event.client.vue
fixes #466 
@il12 сделала инпут цены Number'ом, как ты и советовал. На бэк отправляется строкой, но пока без указания валюты (чтобы не переписывать price handler)
=> St 466: change price input type

frontend/pages/event/[id].vue
fixes #540 
remove margin-bottom for button "connect" if manage buttons're absent
=> Fix 540: remove margin-bottom for button "connect"

backend/src/rest/v1/events/controller.ts
Fix editing events in past (backend part)
=> Fix update events in past (backend)

frontend/constants/defaultValues/time.ts, frontend/pages/postauth/[id].vue
=> Fix token ttl (add maxAge - 30 days)

backend/src/migrations/price-structure-18-07-23.ts, backend/src/models/event.model.ts, backend/src/rest/v1/events/schema.ts, backend/src/server.ts, common/types/event.ts
Change mongoose schema;
Change event type (add separate EventPrice type);
Change swagger schema;
ATTENTION: Remove migration from server.ts right after merge with prod
=> Add migration for new price type;

frontend/nuxt.config.ts
Добавила по описанному [сценарию](https://github.com/nuxt/nuxt/issues/14794), но сжатие на локалхосте идет не для всех файлов.
Я бы посмотрела на тесте, и если не сработает, подключу [модуль сжатия ](https://github.com/Baroshem/compression)
=> 604: add GZip compression

frontend/constants/enums/seo.ts, frontend/pages/limitation_of_liability.vue
микроразметка для юридической информации
=> #514-seo-limitation feat: header seo

backend/src/controllers/user-controller.ts, backend/src/rest/v1/events/controller.ts, backend/src/rest/v1/image/controller.ts, backend/src/rest/v1/image/router.ts, backend/src/rest/v1/location/controller.ts, backend/src/rest/v1/payment-info/controller.ts, backend/src/rest/v1/registration/controller.ts, backend/src/rest/v1/tags/controller.ts, backend/src/rest/v1/timezones/controller.ts, backend/src/rest/v1/user/controller.ts, backend/src/validators/event-validator.ts, frontend/pages/event/[id].vue, frontend/pages/limitation_of_liability.vue, package-lock.json, package.json
=> project name

backend/src/controllers/user-controller.ts, backend/src/rest/v1/events/controller.ts, backend/src/rest/v1/image/controller.ts, backend/src/rest/v1/image/router.ts, backend/src/rest/v1/location/controller.ts, backend/src/rest/v1/payment-info/controller.ts, backend/src/rest/v1/registration/controller.ts, backend/src/rest/v1/tags/controller.ts, backend/src/rest/v1/timezones/controller.ts, backend/src/rest/v1/user/controller.ts, backend/src/validators/event-validator.ts, frontend/pages/event/[id].vue, frontend/pages/limitation_of_liability.vue, package-lock.json, package.json
Reverts openworld-community/ows-events#640
=> Revert "project name"

frontend/pages/index.vue
=> fixes 582: loading-events

frontend/pages/index.vue
Reverts openworld-community/ows-events#648
=> Revert "fixes 582: loading-events"

backend/src/models/event.model.ts, backend/src/rest/v1/events/schema.ts, common/types/event.ts, frontend/components/home/EventPreviewCard.vue, frontend/components/modal/Event.client.vue, frontend/i18n/en-GB.ts, frontend/i18n/ru-RU.ts, frontend/package-lock.json, frontend/pages/event/[id].vue
=> Add event organizer

frontend/app.vue, frontend/components/modal/Event.client.vue, frontend/utils/prices.ts
=> Fix format currency error

frontend/pages/event/[id].vue
=> changed the redirect when deleting the event

frontend/pages/event/form.vue, frontend/stores/event.store.ts
Изменила getters которые ничего не возвращают, и не вызываются в коде, на watch
=> fix/741: getters doesn't work

frontend/i18n/en-GB.ts, frontend/i18n/ru-RU.ts
=> feature 785: add tags to i18n

frontend/i18n/locales/en-GB/footer.ts, frontend/i18n/locales/en-GB/header.ts, frontend/i18n/locales/ru-RU/footer.ts, frontend/i18n/locales/ru-RU/header.ts
=> fix 767: fixed the names of links in the header and footer

frontend/i18n/locales/en-GB/form.ts, frontend/i18n/locales/ru-RU/form.ts
=> fix 882: fixed the link name in the event creation form

frontend/pages/postauth/[id].vue
=> fix 821: fixed the user's redirect to the main page after authorization

frontend/components/home/Filters.vue, frontend/stores/filter.store.ts
не отрабатывают геттеры в filter.store (заменены на action + watch)
=> fix 615: change getters

frontend/components/common/Button.vue, frontend/components/footer/Common.vue, frontend/components/header/Common.vue, frontend/components/header/LanguageSelector.vue, frontend/components/home/EventPreviewCard.vue, frontend/i18n/locales/en-GB/about.ts, frontend/i18n/locales/en-GB/footer.ts, frontend/i18n/locales/ru-RU/about.ts, frontend/i18n/locales/ru-RU/footer.ts, frontend/pages/about.vue, frontend/pages/event/[id].vue, frontend/pages/index.vue
=> fix 884: added alt/title to images and links

frontend/components/home/EventPreviewCard.vue, frontend/i18n/locales/en-GB/footer.ts, frontend/i18n/locales/ru-RU/footer.ts, frontend/pages/event/[id].vue
=> fix 884: fixed adding alt/title to images and links

frontend/components/common/ui/BaseSelect.vue, frontend/components/common/ui/Filter.vue
=> fix 848: select layout fixes

frontend/app.vue, frontend/nuxt.config.ts
=> fix 806: google metrics

backend/src/externalServices/googledocs.ts
Change title from peredelano to peredelanoconf;
=> Add organizer to parser;

frontend/assets/less/colors.less, frontend/components/common/Button.vue, frontend/components/common/ui/BaseSelect.vue, frontend/components/footer/Common.vue, frontend/components/header/Common.vue, frontend/components/modal/ClearEventForm.vue, frontend/components/modal/DeleteEvent.vue, frontend/components/modal/EditProfile.vue, frontend/components/modal/Filter.vue, frontend/components/modal/NeedAuthorize.vue, frontend/components/user/AdditionalBlock.vue, frontend/pages/event/[id].vue, frontend/pages/event/form.vue, frontend/pages/user/index.vue, frontend/pages/user/my-events.vue
=> 885: add buttons layout

frontend/nuxt.config.ts, frontend/package-lock.json, frontend/package.json, frontend/robots.config.ts
=> 888: add robots.txt file

backend/src/externalServices/googledocs.ts, backend/src/models/event.model.ts, backend/src/rest/v1/events/schema.ts, common/types/event.ts
Remove required property from `location.country` and `location.city`; Change swagger schema;
=> Add isOnline field to event;

frontend/components/common/ui/Tag.vue, frontend/components/home/EventPreviewCard.vue, frontend/components/user/EventCard.vue, frontend/pages/event/[id].vue, frontend/services/timezone.services.ts, frontend/utils/dates.ts
=> 894: add display of online events

backend/src/rest/v1/events/controller.ts
=> Remove link uniqueness check;

frontend/assets/less/blocks/form.less, frontend/components/common/ui/BaseInput.vue, frontend/components/user/Login.vue, frontend/components/user/SignUp.vue, frontend/nuxt.config.ts
removed exess code && changed positioning of error label due to visual bugs depending on text size
=> clean up && error label layout fixes

frontend/components/user/SignUp.vue, frontend/components/user/Unauthorized.vue
added flex-dir: column on signup mobile
=> signup error label fix

backend/src/rest/v1/events/controller.ts
Reverts openworld-community/ows-events#947
=> Revert "Localize error"

frontend/components/common/ErrorComponent.vue, frontend/components/common/ImageLoader.vue, frontend/components/common/form/Field.vue, frontend/components/event/Form.vue, frontend/components/event/eventValidationSchema.ts, frontend/constants/defaultValues/validation.ts, frontend/i18n/locales/en-GB/validation.ts, frontend/i18n/locales/ru-RU/validation.ts, frontend/utils/image.ts
changed hint for image formats, added max for price and url
=> Fix 823 image hint

frontend/components/common/ui/Filter.vue, frontend/components/home/EventPreviewCard.vue, frontend/components/home/Filters.vue, frontend/composables/useApiRouter/filters.ts, frontend/stores/filter.store.ts
adjustments for query && event poster date display for one-day events
=> adjustments for query && event poster date display for one-day events

frontend/components/common/ImageLoader.vue
on del image button submit form (create/edit event), having type 'buttton' this button do not submit form
=> button del image changes type and get button

frontend/.env.dev, frontend/app.vue, frontend/utils/meta.ts
#986. fixed omg url for social (remove API from address)
=> changed omg url for social

frontend/components/library/Autocomplete.vue, frontend/components/library/Select.vue, frontend/components/library/ui/ItemSearch.vue, frontend/components/library/ui/ItemSelect.vue
removed hover from select/search item && added popper onclick && adjusted checkmark icons for select && fixed modelValue clear
=> ux improves + stylle fixes

frontend/assets/less/blocks/input.less, frontend/components/common/Button.vue, frontend/components/common/ui/Filter.vue, frontend/components/header/Common.vue
remove condition where back button goes back on route history
=> Filter icons fix && header back-button fix

common/const/tags.ts, common/types/event.ts, frontend/components/common/TagList.vue, frontend/i18n/locales/en-GB/event.ts, frontend/i18n/locales/ru-RU/event.ts
=> created new list of tags

frontend/stores/location.store.ts
=> -removed Kirgisstan from create event

frontend/i18n/locales/en-GB/event.ts
=> fixed for adults-18+

frontend/components/common/EventDetails.vue, frontend/components/home/EventPreviewCard.vue
=> event date wrapped into client only

frontend/components/common/ui/LoadSpinner.vue, frontend/components/event/Form.vue, frontend/components/footer/Common.vue, frontend/components/header/Common.vue, frontend/components/home/CardList.vue, frontend/components/home/Filters.vue, frontend/composables/useApiRouter/filters.ts, frontend/nuxt.config.ts, frontend/pages/event/edit-[editId].vue, frontend/pages/index.vue, frontend/stores/filter.store.ts
Loader has absolute position - to not shift cards between renders
#1069
=> Feature 1069 loader

frontend/components/event/Form.vue, frontend/pages/event/edit-[editId].vue
#1074 
it can be added to demo
=> fixed pressable button second time creating double event (can be added to demo too)

frontend/components/common/ui/Filter.vue, frontend/components/home/Filters.vue, frontend/components/library/ScrollArea.vue, frontend/components/library/Select.vue, frontend/components/library/ui/ItemSelect.vue
=> fixed scroll color on hover and added scoped for select

frontend/components/header/Common.vue
=> return back button back in header from profile to user, not home

frontend/components/common/ImageLoader.vue
#1112
image aspect ratio like on main page, size: with: 248px
=> changed image size while creating event

frontend/components/event/Form.vue, frontend/components/event/FormLocation.vue, frontend/components/library/Autocomplete.vue, frontend/pages/event/edit-[editId].vue, frontend/utils/events.ts
стор к ивентам написан непоследовательно, initialValues вне стора, где нельзя зафетчить сразу getTimzone для Сербии, тк useFetch требует окружение vue 
перерабатывать стор в рамках этой таски не буду, поэтому пока вот так полу-костыльно
=> locked offline tz 

frontend/components/common/Button.vue, frontend/components/common/NavLink.vue, frontend/components/header/Common.vue, frontend/components/header/SidebarItem.vue, frontend/components/header/constants.ts, frontend/components/header/navigation/Main.vue, frontend/components/header/navigation/Sidebar.vue, frontend/components/library/Alert.vue, frontend/components/library/ui/ModalDialogContent.vue, frontend/components/modal/NeedAuthorize.vue, frontend/i18n/locales/en-GB/global.ts, frontend/i18n/locales/ru-RU/global.ts, frontend/layouts/profile.vue
=> added create event buttom in header

frontend/components/modal/ui/ModalRawSection.vue, frontend/middleware/auth.global.ts, frontend/pages/event/edit-[editId].vue, frontend/pages/postauth/[id].vue, frontend/pages/user/profile.vue, frontend/stores/event.store.ts
=> removed header on create event page - fix to layout

frontend/assets/less/blocks/input.less, frontend/components/common/Button.vue, frontend/components/common/Icon.vue, frontend/components/common/ui/DateTimepicker.vue, frontend/components/common/ui/Filter.vue, frontend/components/common/ui/Tag.vue, frontend/components/header/Common.vue, frontend/components/header/navigation/Main.vue, frontend/components/home/Collapsible.vue, frontend/components/home/Filters.vue, frontend/components/library/Collapsible.vue, frontend/error.vue, frontend/i18n/locales/en-GB/home.ts, frontend/i18n/locales/ru-RU/home.ts, frontend/layouts/default.vue, frontend/stores/filter.store.ts, frontend/utils/index.ts
=> Feature 1114 remove search

frontend/assets/less/blocks/input.less, frontend/components/common/ui/DateTimepicker.vue, frontend/components/common/ui/Tag.vue, frontend/components/header/Common.vue, frontend/components/home/Collapsible.vue, frontend/components/home/Filters.vue, frontend/components/library/Select.vue, frontend/pages/event/edit-[editId].vue, frontend/stores/filter.store.ts
calendar button works as usual - click on icon is opening picker, in select button-close works on hover, focus-visible-getting green'
=> fixed calendar button and select button-close

frontend/components/common/ui/DateTimepicker.vue, frontend/components/home/Filters.vue
added check if no data choosen when datapicker on main opened and then closed
=> fixed problem with range datepecker when no data choosen 

frontend/app.vue, frontend/utils/meta.ts
on the pasis of demo branch, instead of the name uses path - to have real path and not name like index in resulting path in metatag
=> changed name into path for hreflang

frontend/components/library/MobileSelect.vue
for demo, for main only commit
=> city on main on mobile in filter in local language

frontend/components/home/CardList.vue
Headings on main on mobile separated from the left border
=> headings on main on mobile added margin on the left

frontend/components/header/navigation/Main.vue
text2 согласно фигме поставлен в header на десктопе
=> fixed font in navigation menu

frontend/components/common/ui/Tag.vue, frontend/components/detailes/Tags.vue, frontend/components/filters/Wrapper.vue, frontend/components/search/EventCardsList.vue, frontend/components/search/EventPreviewCard.vue
=> tags sizes fixed

frontend/components/user/MobileNavigationMenu.vue, frontend/components/user/NavigationMenu.vue
=> Add icon-color props to the userpage navigation menu

backend/src/rest/v1/auth/controller.ts, frontend/app.vue, frontend/components/header/LanguageSelector.vue, frontend/constants/enums/common.ts
Reverts openworld-community/ows-events#1389
=> Revert "Add special lang cookie for sending to backend through requests from …"

frontend/components/detailes/Image.vue, frontend/components/detailes/Info.vue, frontend/pages/event/[id].vue, frontend/utils/dates.ts, frontend/utils/ld-json.ts
=> fixed dateStart -n ld-json

frontend/components/detailes/Image.vue, frontend/components/detailes/Info.vue, frontend/pages/event/[id].vue, frontend/utils/dates.ts, frontend/utils/ld-json.ts
console removed
fixed dateStart -n ld-json
=> HOTFIX: ld-json time fix

frontend/components/detailes/Description.vue, frontend/components/detailes/Items/Title.vue
=> Change word breaking to break-word;

frontend/components/common/Button.vue, frontend/components/common/LikeButton.vue, frontend/components/search/EventPreviewCard.vue
=> 1420 - Добавление и удлаение из избранного с главной страницы

frontend/components/footer/Common.vue
closes #1471 
Component need refactoring;
=> 1471 - Исправление расположения иконок в футере на планшете

backend/src/rest/v1/events/schema.ts
Revert "1585 - валидация на бэкенде"
This reverts commit 5652a41956c4afc87312b193dee54975384c6a50.
Revert "Feature/1585 auth and event validation backend (#1593)"
This reverts commit 010accb3f024e4054e1e978964df6fdb55210c7d.
Revert "Feature/1585 auth and event validation backend (#1594)"
This reverts commit ea475e747817a0065d466f702ae8d6b4020a00d8.
=> Revert backend validation

.github/workflows/build-and-push-demo.yml, .github/workflows/build-and-push-prod.yml, .github/workflows/build-and-push-test.yml
Уведомления по успешному deploy-demo/test/prod шагу
сигнализируют о успехе или неуспехе при мерже веток из  Пул реквестов
=> 1610 - Уведомления для телеграма после успешного завершения экшена
